print("Digite um número para A:")
local A = io.read("*n")
print("Digite um número para B:")
local B = io.read("*n")
print("Digite um número para C:")
local C = io.read("*n")
print("Digite um número para D:")
local D = io.read("*n")
print(A+B, A+C, A+D, B+C, B+D, C+D)
print("MULTIPLICAÇÃO", A*B, A*C, A*D, B*C, B*D, C*D)